version: '3.9'

services:
  mysql:
    image: 'mysql:latest'
    container_name: 'java-mysql'
    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./scriptsForDB:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "mysql -uroot -p1234 -D shop -e 'SELECT 1;'" ]
      interval: 10s
      retries: 10
    networks:
      - testnetwork1

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/shop
    networks:
      - testnetwork1
    depends_on:
      mysql:
        condition: service_healthy

networks:
  testnetwork1: